### ISSUE TITLE
Find usages does not work across modules

### ISSUE THREAD

**Issue by kakarukeys** [srusskih/SublimeJEDI#134]
Hi,

I have just installed SublimeJEDI and configured it according to the doc.

I have a symbol that is used in module B, defined in module A.

When I do Ctrl+Shift+G, it correctly finds the definition in module A. 

When I then do Alt+Shift+F, it only lists the usages in module A, the usage at module B is missing.

**Comment by srusskih** [comment]
It's depends on how it used.

Base class used in the module.
<img width="909" alt="base_class_usage" src="https://cloud.githubusercontent.com/assets/340727/26723828/0b898624-479f-11e7-9f31-b0d5cafa003c.png">

Base class used across the project.
<img width="894" alt="base_class_usages_across_project" src="https://cloud.githubusercontent.com/assets/340727/26723827/0b8852ea-479f-11e7-9de6-64263424502a.png">

Child classed, defined, imported (in `sublime_jedi/__init__.py`) but never **used**
<img width="872" alt="child_class_usage" src="https://cloud.githubusercontent.com/assets/340727/26723826/0b84f4d8-479f-11e7-88dc-1ffbd9aace90.png">

Hope this will helps.
