### ISSUE TITLE
Autocompletion after import statement

### ISSUE THREAD

**Issue by pe224** [srusskih/SublimeJEDI#150]
Hey there.
If I type "import " and open the auto-completion, all of the module names are shown as modules.
But as soon as I type a letter, the list does not adapt, but just disappears.
Also typing "import B" does not show e.g. BaseHTTPServer. The list seems to pop up for a very short time, but then disappear.
I'm using Sublime Text 3 on Mac OS 10.7
Will be happy to help, SublimeJEDI is IMHO the best code completion for Python.

EDIT:
Just tested it on a Windows machine with both ST versions. It seems it's a ST2 vs ST3 issue.
On ST2, it is working as expected.

EDIT 2:
The same fix as for a [similar issue in SublimeCodeIntel](https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/346) applies, connected to the parameter `'disable_auto_insert'` in the call to `"auto_complete"`.
In file `<jedi dir>/sublime_jedi/completion.py` in line 196, change

``` python
view.run_command("auto_complete", {
    'disable_auto_insert': True,
    'api_completions_only': False,
    'next_completion_if_showing': False,
    'auto_complete_commit_on_tab': True,
})
```

to

``` python
view.run_command("auto_complete", {
    'disable_auto_insert': True,
    'api_completions_only': False,
    'next_completion_if_showing': False,
    'auto_complete_commit_on_tab': True,
    'disable_auto_insert': False,
})
```

I have no idea what this does, but now it's working ;)

**Comment by VSsmall** [comment]
Hello, I have a same question with pe224. And I find st3 Python.sublime-package, but I don't know how to replaced it?
is it delete this zipped package and put the Completion Rules.tmPreferences in that folder?

**Comment by srusskih** [comment]
".sublime-package" is a zip file.
replace it with unzipped package, now it's able to replace Completion Rules. 
Hope it helps.

**Comment by christophemcguinness** [comment]
Thanks @pe224, your edit 2 worked for me using sublime 3 and sublimecodeintel.
