### ISSUE TITLE
Function doesn't fill all parameters

### ISSUE THREAD

**Issue by 1st** [srusskih/SublimeJEDI#158]
Hello.

I have fresh install of **SublimeJedi** *(named Jedi in Sublime Package Control)*. I added this code to **Sublime Text -> Preferences -> Package Settings -> Jedi -> Settings - User**

```python
{
    "auto_complete_function_params": "all"
}
```

But when I create this code I see that only required parameter filled, and all not required parameters isn't present:

```python
def xxx(a, b=1, c=True):
    pass

xxx(a)
```

Can you please provide me help in this? Because it isn't work as expected.

**Comment by srusskih** [comment]
To allow change that settings on the fly, we have to pass this settings on each completion request.
On stop passing this option to daemon at all and work with complation options on the client-side. 

#169 created for the feature
