### ISSUE TITLE
bug：jedi to sublime collapsed

### ISSUE THREAD

**Issue by edmond1948** [srusskih/SublimeJEDI#160]
使用sublime jedi插件后，无法在py文件中输入以下代码：
After using sublime jedi plugin, you can not enter the following code in the py file:
Platform：windows7 / centos6.4
Sublime：2.0.2

/\* python code */
import datetime
datetime.timedelta(days...)

**Comment by Marrin** [comment]
I can confirm that on ST2 on Ubuntu.  ST2 segfaults if I start typing the arguments name.

**Comment by gukoff** [comment]
The lines above do not work for me, but I am getting the similar behaviour here:
https://github.com/DamnWidget/anaconda/issues/317
This is likely the same issue, since Anaconda is using Jedi internally and the crash depends on the module imports I do.
