### ISSUE TITLE
SublimeJEDI not showing correct autocompletions

### ISSUE THREAD

**Issue by nulinspiratie** [srusskih/SublimeJEDI#162]
I've recently installed SublimeJEDI. However, it is not showing me all the autocompletion possibilities (i.e. variables previously declared and functions within the same script).

What I expect SublimeJEDI to do is when, for instance I type:
numpy.ar <TAB>
Is that it gives me a list of possible functions of numpy, including array and arange. However I do not see these in the list.

Currently the part of my user settings relevant to python is as follows:

```
"python_interpreter_path": "C:/Python27/python.exe",
"env":
{
    "PYTHONPATH":"C:/Python27:C:/Python27/Lib/site-packages"
},
```

The python_interpreter_path was necessary because otherwise it would not find the python interpreter. The part about pythonpath I'm not sure of. I expected this to cause SublimeJEDI to find the right packages, but it does not seem that way.

Am I missing something?

**Comment by porinz** [comment]
Bit late to the party, but I think I can shed some light on this.

Ran into the same problem this morning configuring SublimeJEDI to use a virtualenv instance for one of my projects. For Windows installs, turns out you've gotta use the double-backslash style when setting the interpreter path:

    "settings": {
        "python_interpreter": "$project_path\\venv_thetis\\Scripts\\python.exe"
    }
