### ISSUE TITLE
Autocomplete python code blocks in a markdown file?

### ISSUE THREAD

**Issue by shaunpatel** [srusskih/SublimeJEDI#170]
Is it possible to modify this to autocomplete within fenced python code blocks within a markdown file?

**Comment by srusskih** [comment]
it's depends on source file scope. if python code block can be somehow detected with "ST scope", then it's possible

You can try to experiment with https://www.sublimetext.com/docs/3/api_reference.html#sublime.View scope_name(point) to detect if python code block has a specific scope to enable completion there
