### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by johnmellor** [srusskih/SublimeJEDI#173]
The last tag on https://github.com/srusskih/SublimeJEDI/releases is 0.7.0, from May 2014; hence this is still the version that Package Control is distributing. But there have been useful changes since then, like upgrading to Jedi 0.8.1, and [adding][1] the sublime_jedi_docstring functionality.

Has there been a version since then that is stable enough to tag and distribute?

[1]: https://github.com/srusskih/SublimeJEDI/commit/bfeaf5194bbc8e2dc2bf3f8f4922556ceea96b8d

**Comment by srusskih** [comment]
hm. good idea. will do it today

**Comment by srusskih** [comment]
Done (=

**Comment by johnmellor** [comment]
Thanks, 0.8.0 works great so far!

**Comment by srusskih** [comment]
nice to hear it (:
