### ISSUE TITLE
jedi goto errors

### ISSUE THREAD

**Issue by diveru4i** [srusskih/SublimeJEDI#177]
For some reasons in one of the recent versions of the package the goto functionality stopped working for me. What could it be?

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./sublime_jedi/go_to.py", line 84, in run
  File "./sublime_jedi/utils.py", line 211, in ask_daemon
  File "./sublime_jedi/utils.py", line 121, in __init__
  File "./sublime_jedi/utils.py", line 233, in get_settings
  File "./sublime_jedi/utils.py", line 325, in expand_path
ValueError: zero length field name in format
```

**Comment by srusskih** [comment]
Do you use master-branch version or 0.8.0 ?

**Comment by diveru4i** [comment]
Reinstalled it via Package Control.
0.8.0

**Comment by srusskih** [comment]
thx for the answer.
looks like same issue was fixed in master-branch.
will create 0.8.1 as soon as can

**Comment by diveru4i** [comment]
The exact problem is with this line
```python
subl_vars['$project'] = view.window().project_file_name()

>> 'Window' object has no attribute 'project_file_name'
```

**Comment by srusskih** [comment]
ok. looks like plugin is broken for ST2

**Comment by diveru4i** [comment]
The problem exists only in 0.8.0. 
Master branch works great as before.

**Comment by srusskih** [comment]
that's really odd, case `project_file_name()` exists only in ST3

**Comment by srusskih** [comment]
#178 fixed

**Comment by srusskih** [comment]
0.8.1 created before #178 fix
