### ISSUE TITLE
Attempt to define __repr__ or __str__ methods causes segfault

### ISSUE THREAD

**Issue by Rawieo** [srusskih/SublimeJEDI#179]
Definig `__repr__` or `__str__` method causes segfault:
- After writing 2-nd symbol of first argument in defenition of `__repr__` method
- After writing 3-rd symbol of first argument in defenition of `__str__` method

**Comment by srusskih** [comment]
Need more info

**Comment by Rawieo** [comment]
uname -srvmo: `Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux`

**Comment by srusskih** [comment]
what sublime text version ?
what version plugin (from master of tag) ?

**Comment by Rawieo** [comment]
Sublime Text: Version 2.0.2, Build 2221
SublimeJEDI: v0.8.1

**Comment by srusskih** [comment]
thx. will test it

**Comment by srusskih** [comment]
fixed
