### ISSUE TITLE
Double commas in completion output

### ISSUE THREAD

**Issue by adammhaile** [srusskih/SublimeJEDI#180]
With the latest version of the plugin and ST3 Build 3083 I'm seeing double commas between params everytime it does an autocompletion. For example:

The following function:

    def pullIDs(data, doSingle = True, idCol = 'id'

autocompletes to:

    pullIDs(data,, doSingle=True,, idCol='id')

My extension settings are:

```
{
    "auto_complete_function_params": "all",
    "sublime_completions_visibility": "default"
}
```

**Comment by jmagnusson** [comment]
Would be nice with a release for this!

**Comment by srusskih** [comment]
Does the fix works for you ? If yes, I will release as soon as possible.

**Comment by jmagnusson** [comment]
Works fine for me in ST3!

**Comment by srusskih** [comment]
@jmagnusson 0.8.2 released (= enjoy!

**Comment by jmagnusson** [comment]
Thanks, works great.
