### ISSUE TITLE
Jedi gets into infinite loop on Goto

### ISSUE THREAD

**Issue by kkujawinski** [srusskih/SublimeJEDI#185]
For some files Jedi gets into infintie loop on Goto action.

It happens on Jedi version embedded in SublimeJEDI, but it doesn't on PyPi 0.9.0 Jedi version.

Test case file and Pull request on theirs way.

**Comment by kkujawinski** [comment]
1. Python file:
```
from datetime import datetime

def test_abc(a):
    u"""
def abc():
    return 'abc'"""

def test_xyz(db):
    pass
```
2. Call Goto command on datetime
3. Daemon gets into infinite loop

**Comment by kkujawinski** [comment]
PR:
https://github.com/srusskih/SublimeJEDI/pull/186

**Comment by srusskih** [comment]
Thanks (= 
I made some comment to PR.

**Comment by srusskih** [comment]
Will close the issue due to merged PR
