### ISSUE TITLE
tkinter autocomplete

### ISSUE THREAD

**Issue by rokf** [srusskih/SublimeJEDI#187]
I have a problem with **tkinter** having no auto complete but **Tkinter** has it.

Someone explained the same issue here https://github.com/davidhalter/jedi/issues/583

My current version of SublimeJEDI is **0.8.2** (Package Control)

**Comment by srusskih** [comment]
Just created new release with latest code https://github.com/srusskih/SublimeJEDI/releases/tag/0.8.3

I think it will appears soon in PC

**Comment by rfajfar** [comment]
Damn I should have thought of this.

I didn't set the default python interpreter for the sublime project to be python3 instead of python.

My `.sublime-project` file looks like this now:

```
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings": {
		"python_interpreter" : "/usr/bin/python3"
	}
}
```

**tkinter** completion works now.
