### ISSUE TITLE
Sometimes, completions are undone for seemingly no reason

### ISSUE THREAD

**Issue by FichteFoll** [srusskih/SublimeJEDI#191]
In some situations, typing fast and then using `tab` triggers a completion, which is then undone shortly afterwards. Hitting tab again does not fix it either. I have to `ctrl+space` and then use tab so the completion is not undone.

I don't know if anyone else has experienced this, but I get this semi-often (few times a day) and it's pretty annoying. Since this only happens in Python files and Jedi is the only completion package I use, it must be Jedi's fault.

**Comment by mandx** [comment]
It is SublimeJEDI's fault, [see here](https://github.com/srusskih/SublimeJEDI/blob/master/sublime_jedi/completion.py#L208). And yes, it is annoying: sometimes I use tab-completion to write similar symbols in the code; for example, I have this method `def test_this_function`, then I want to write `def test_this_class` and without JEDI I can write `def test_th` and then hit `Tab` to get `def test_this_function` then replace "function" with something else.

**Comment by srusskih** [comment]
Yeah, there was an issue in ST2 #87.
When you hit a `Tab` after a dot it inserts best match snippet (`import os; os.` -> `import os; osself.`). That's why that was done.

Looks like ST3 doe not have this issue, but new one appeared :D

Will try to fix it.
