### ISSUE TITLE
Completions are always collected twice, if there is a prefix

### ISSUE THREAD

**Issue by FichteFoll** [srusskih/SublimeJEDI#192]
With the following plugin, I revealed that the completions are always collected two times and you can also observe the completion popup showing after the first time very briefly.

``` py
import time, sublime, sublime_plugin

class Listener(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        time.sleep(2)
        print("queried completions")
        return list("abcdefg")
```

When you trigger the completions popup on the new line, this is behaving as expected (one line of "queried completions", 2s wait tim). However, if the popup is opend when there is a prefix (e.g. when typing `t`), the panel takes 2s to appear briefly (prints to console) and then another 2s to finally appear for real (prints again).

I determined this to be SJedi's fault because it only happens in Python files and when SJedi is not disabled.

Possibly related to #191.

**Comment by srusskih** [comment]
have updated completion behavior in #244
