### ISSUE TITLE
Doesn't work on MacOS

### ISSUE THREAD

**Issue by 1st** [srusskih/SublimeJEDI#198]
Hello.

I use latest version of **SublimeText** _(build 3103)_. After installation of `SublimeJEDI` and restart of **SublimeText** is seems like plugin isn't working: built-in autocompletion doesn't work and **JEDI** also don't work. Third to reinstall plugin few times and restart **SublimeText** - but it didn't helped.

I also played with **Sublime Anaconda** - they also use **JEDI** under the hood - but in their plugin all work as expected. Can you please fix this plugin? Because I prefer too use separate templates and don't like to use **IDE-like** plugins like **Anaconda** (I use **SublimeLinter** and some small plugins, and need to have one more plugin to auto-completion for external python libraries like **Django**).

If you need help from me to get traceback or something - please let me know and I will provide help from my side.

Thanks.
Anton

**Comment by srusskih** [comment]
Yeap, traceback & settings would be useful. Thanks.

**Comment by 1st** [comment]
Hi. I don't know how to gather this information, but I will try. If you can provide help about how to collect this information - it will be very helpful.

I have prepared this [gist](https://gist.github.com/1st/4431e1e02e1b568dcf827dde16a8910d). If you need additional info - I will extend this gist with more detailed information, As I see - we need to enable debug mode somehow to show more verbose information about plugin.

PS. Добре бачити що розробник цього плагину також як і я зі Львова ;-) Нажаль не знайшов як з тобой можно звонтактувати на фейсбуці чи по емейлу, так може було би швидше та простіше.

**Comment by 1st** [comment]
I guess that it can be conflict with one of installed third-party plugins, like `SublimeLinter`. I will try to disable all plugins and try `SublimeJEDI` in work.
