### ISSUE TITLE
insert all function arguments on autocomplete not work

### ISSUE THREAD

**Issue by cloudnix** [srusskih/SublimeJEDI#202]
Hi i try this but can't work

```
# complete result
func(a, b, c, d=True, e=1, f=None)

# sublime_jedi.sublime-settings
{
    "auto_complete_function_params": "all"
}
```

**the auto complete function parameters not work if use function from another script file (use import)**
please help, thanks

**Comment by gabrielarpino** [comment]
Bump, also having this problem

**Comment by nejdetckenobi** [comment]
Having this problem, too. ST3.

**Comment by srusskih** [comment]
Could You please provide some steps to reproduce. Thanks.

**Comment by imdadahad** [comment]
Any update on this?

**Comment by imdadahad** [comment]
Any ideas, this one is a dealbreaker.

**Comment by LynnHo** [comment]
I met the same problem.

**Comment by srusskih** [comment]
I have updated a completion logic a bit and agruments completion also.
please check #244 if it works for you
