### ISSUE TITLE
autocompletion on subpackages not working

### ISSUE THREAD

**Issue by iliasptr** [srusskih/SublimeJEDI#205]
Hi,
I cannot get autocompletion to work on some custom python packages. I have added my custom package path in user sublime settings as:
```
"python_package_paths": [
     // path for package
    "/home/ilias/modules/lib/python2.7/site-packages/moduleA",
    ],
```

Autocompletion works fine for the functions declared in the `__init__.py` file of `moduleA` by writing:
```
import ModuleA as MA
MA.read_files()
```

In the same directory however, I also have some other .py subpackages (e.g. `mergefunct.py`) which include additional functions. In my main code, I can normally import and call these as:
```
import ModuleA.mergefunct as mergefunct
mergefunct.perform_merging()
```

Autocomplete locates the package `mergefunct` under `ModuleA`, but as soon as I press 'dot' to use the functions inside it, it doesn't detect the functions at all. Furthermore, after this autocompletion no longer works even for normal python functions as `math` or `numpy` etc. and I need to restart sublime to get it working again.

**Comment by srusskih** [comment]
Sounds not good.

**Comment by jurisbu** [comment]
Same here. This needs a fix!

**Comment by srusskih** [comment]
@jurisbu could you please add more context?

**Comment by srusskih** [comment]
@iliasptr do you use a system python (2.7.x as I see)?

**Comment by srusskih** [comment]
Each item from `"python_package_paths"` will added to `sys.path` as `sys.path.insert(0, extra_path)`.
After this, python would be able to discover extra packages.

But, please note that Python will goes through the directories to search for modules and files.
In other words, "extra path" is a directory with extra packages and modules not a direct path to package or module.

**Comment by jurisbu** [comment]
@srusskih Sublime Text 3 dev build 3142.
Similar to what @iliasptr describes I have a Python package (directory) with Python modules (like module.py). I do not get completions for classes defined in package.module. I can try creating example dummy project with a minimal use case as example.

**Comment by srusskih** [comment]
@jurisbu please create. that will helps a lot with investigation.

**Comment by jurisbu** [comment]
@srusskih Excellent, can confirm that adding `python_package_paths` as per you suggestion indeed resolves my issue. Thanks!

**Comment by srusskih** [comment]
@jurisbu can I ask? did you got why it works?

**Comment by srusskih** [comment]
@iliasptr please reopen the issue if you still have a problem with this.
