### ISSUE TITLE
How to use autocomplete on standard lib?

### ISSUE THREAD

**Issue by 1st** [srusskih/SublimeJEDI#206]
Out of the box autocompletion for stdlib doesn't work. I tried to configure project settings to this:

```json
{
	"settings": {
		"python_interpreter": "~/.virtualenvs/myproject/bin/python",
		"python_package_paths": [
			"~/.virtualenvs/myproject/lib/python2.7/",
			"~/.virtualenvs/myproject/lib/python2.7/site-packages/"
		]
	}
}
```

When I do this:
```python
import os
import sys

os.
sys.
```

no autocompletion after the dot. How to fix it?

Used MacOS 10.12.4, python 2.7, latest sublime text 3 and jedi plugin.

**Comment by srusskih** [comment]
https://github.com/srusskih/SublimeJEDI#autocomplete-on-dot

**Comment by 1st** [comment]
Thank you @srusskih. But it looks not too obvious to make this configuration after installing the plugin.

I think that it will be good to have it out-of-the-box to have autocomplete on the dot. It's why people installing this plugin, then trying to have auto-completion on the dot... and remove it, because it's not working.

Thanks for solving my particular case!
