### ISSUE TITLE
traceback in console on shift-ctrl-g:  local variable 'module_path' referenced before assignment

### ISSUE THREAD

**Issue by sunew** [srusskih/SublimeJEDI#214]
Jedi - Python autocompletion.sublime_jedi.utils: 2017-08-03 16:58:45,644: ERROR   : `JediFacade.get_goto` failed
Traceback (most recent call last):
  File "daemon.py", line 130, in get
    return getattr(self, 'get_' + action)()
  File "daemon.py", line 136, in get_goto
    return self._goto()
  File "daemon.py", line 224, in _goto
    definitions = self.script.goto_assignments()
  File "../jedi/api/__init__.py", line 378, in goto_assignments
    results = self._goto()
  File "../jedi/api/__init__.py", line 434, in _goto
    definitions = self._evaluator.goto(name)
  File "../jedi/evaluate/__init__.py", line 354, in goto
    modules = imports.ImportWrapper(self, name).follow(is_goto=True)
  File "../jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "../jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "../jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "../jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "../jedi/evaluate/imports.py", line 281, in _do_import
    bases = self._do_import(import_path[:-1], sys_path)
  File "../jedi/evaluate/imports.py", line 316, in _do_import
    if module_path is None:
UnboundLocalError: local variable 'module_path' referenced before assignment

**Comment by srusskih** [comment]
Could you please update Jedi (the jedi lib) to different version and check if exception still there?

**Comment by sunew** [comment]
how do I do that? Just a drop-in replacement inside ~/.config/sublime-text-3/Packages/Jedi - Python autocompletion folder?

**Comment by sunew** [comment]
Ok I cloned jedi somewhere tmp and then copied the jedi folder to the  "~/.config/sublime-text-3/Packages/Jedi - Python autocompletion"-folder, replacing jedi.

It works! The problem has gone away.

Also regarding https://github.com/srusskih/SublimeJEDI/issues/215 - here the problem is also solved.

Super! :)

**Comment by srusskih** [comment]
did you use latest jedi version ?

**Comment by sunew** [comment]
I used a clone of master. 
Maybe I ought to test it on the latest released version, 0.10.2 - I will do this now...

**Comment by sunew** [comment]
OK I can confirm that it works with jedi 0.10.2

**Comment by srusskih** [comment]
https://github.com/srusskih/SublimeJEDI/blob/master/jedi/__init__.py#L39 jedi was updated to 0.10.2 in master and now in SublimeJedi 0.10.0

**Comment by sunew** [comment]
@srusskih thank you! :)
