### ISSUE TITLE
v0.10.0 installs additional packages into ST3/Packages directory

### ISSUE THREAD

**Issue by pe224** [srusskih/SublimeJEDI#216]
After the (automatic) update to SublimeJedi 0.10.0 there are the following additional packages installed into `Sublime Text 3\Packages`:

- markupsafe
- mdpopups
- pygments
- python-jinja2
- python-markdown

Is this necessary?
Before, sublimeJedi (or Jedi itself) seemed to work fine without them.

**Comment by srusskih** [comment]
Yeap, packages are required for new tooltips highlighting 
Packages was add in #210 as dependencies. 

I think we can rid of them in future releases when tooltips would improved.

**Comment by pe224** [comment]
@srusskih Ok, thanks for the answer.
Do I have to activate the nice output somewhere? For me it's showing
![popup](https://user-images.githubusercontent.com/8567333/29064416-2b6df1fa-7c29-11e7-940a-2bc5fe80b216.png)

**Comment by srusskih** [comment]
There is no any options, for now. It should be activated automatically if your editor version is greater then 3118.

PS: https://github.com/facelessuser/sublime-markdown-popups uses API features from ST3 Beta 3118+

**Comment by pe224** [comment]
On http://facelessuser.github.io/sublime-markdown-popups/ it even says ST3 3124+
But anyways, my ST is 3126 (latest stable), so it should work...

**Comment by srusskih** [comment]
Maybe @deathaxe could help you?

**Comment by srusskih** [comment]
It's really interesting, where there highlighting (:

**Comment by pe224** [comment]
Ah, sorry. The screenshot above was fro sublime_jedi_docstring command, not the on_hover.
But when I try on_hover it looks the same.
I think it is calling mdpopups, but the formatting seems gone.
(a simple `mdpopups.show_popup(view, "This is a test")` gives me a similar-looking popup window)

**Comment by deathaxe** [comment]
You may try to add the following key to your _Preferences.sublime-settings_ even though it should be the default with latest releases of mdpopups.

```
"mdpopups.use_sublime_highlighter": true,
```

**Comment by pe224** [comment]
@deathaxe Thanks. It enabled the highlighting.
Is there still a small issue with the formatting? Shouldn't the top line be a larger font than the rest?
Do I have to customize it or are the default settings not loaded properly?
![image](https://user-images.githubusercontent.com/8567333/29096211-34cd56c6-7c94-11e7-9bc2-177a53a32991.png)

**Comment by deathaxe** [comment]
What you see is the default style of a code view created by mdpopups.

You can modify all aspects of tooltips created with mdpopups by creating a _Packages/User/mdpopups.css_ and either place global or package specific rules to it.
To increase the font-size of the highlighted code for jedi only, you'll need to add the following rule.

```css
.jedi .highlight {
    font-size: 1.1rem;
}
```

Following rule would apply to all tooltips created by mdpopups.

```css
.mdpopups .highlight {
    font-size: 1.1rem;
}
```

Each package may use a wrapper-class when creating mdpopups to provide package specific styling rules. SublimeJEDI uses `.jedi`. GitGutter uses `.git-gutter`.

For further details about styling please refer to mdpopups' documentation http://facelessuser.github.io/sublime-markdown-popups/styling. The package comes with a default.css as a cheatsheet  for available rules.

**Comment by srusskih** [comment]
@deathaxe I bet we should place this "how to" in to readme-file
