### ISSUE TITLE
How to change autocomplete python bin?

### ISSUE THREAD

**Issue by toplinuxsir** [srusskih/SublimeJEDI#220]
How to change autocomplete python bin?

**Comment by srusskih** [comment]
sorry, what you mean?

**Comment by toplinuxsir** [comment]
I want to modify /usr/bin/python to autocomplete and change to another virualenv such as : /custom_dir/python/bin/python
how to ?
Thanks

**Comment by srusskih** [comment]
We have a section about this in README - https://github.com/srusskih/SublimeJEDI#python-interpreter-settings

Shortly:
add to your `.sublime-project`-file next settings

```
"settings": {
        "python_interpreter": "/path/to/virtual/bin/python"
}
```
