### ISSUE TITLE
Parameters with 'param'

### ISSUE THREAD

**Issue by genbits** [srusskih/SublimeJEDI#221]
Same issue as https://github.com/srusskih/SublimeJEDI/issues/218

Sublime version 3 build 3143
Python 2.7.10
Jedi reinstalled using the package manager

**Comment by srusskih** [comment]
@genbits what the version of the package ?

**Comment by genbits** [comment]
0.10.1

**Comment by srusskih** [comment]
sorry can not reproduce.

and this issue was only for python3.

**Comment by genbits** [comment]
you can close this one too. solving #222  fixed this one too
