### ISSUE TITLE
functions signature popups have loong spaces between arguments

### ISSUE THREAD

**Issue by nsklaus** [srusskih/SublimeJEDI#229]
as the title says:
functions signature popups have loong spaces between arguments.
i am forced to scroll horizontaly to see the whole popup. 

please check attached screenshot.
![arcade_jedi_tooltip](https://user-images.githubusercontent.com/6810861/32416282-1f26964a-c247-11e7-9403-86ed102760f0.png)

about my environment: 
the framework is 'python arcade library', on st3, python3, using ubuntu 17.10 (kde).

**Comment by srusskih** [comment]
@deathaxe have you had similar issues?

**Comment by deathaxe** [comment]
If I'd to guess I would say, the function arguments are formatted with hanging indention. Jedi just removes the line-break but keeps spaces as is. I saw Jedi having issues with multi-line signatures several times. It either cuts signatures off then or moves them strangely.

**Comment by srusskih** [comment]
should be fixed in #235
