### ISSUE TITLE
Can't Install Jedi -Autocomplete in Sublime Text 3

### ISSUE THREAD

**Issue by amith1108** [srusskih/SublimeJEDI#232]
Hi,
I'm trying to install the jedi autocomplete package in Sublime Text 3. Each time I try to install it using Package Control it just doesn't complete installation even after several HOURS!!!

It shows me no error messages . The package just doesn't install .

I've installed Various Packages but never faced this issue.It just Keeps displaying  at the bottom of the Sublime Text as Installing but never completes the installation.

How to solve this problem?
Is there any other way to install the package?

**Comment by psmolak** [comment]
Same issue.

I've noticed this line in console:
`Package Control: The dependency 'mdpopups' is not available`

**Comment by bchamand** [comment]
Same issue for me...
I can't install 'mdpopups' va the the package control..

Build 3143

**Comment by srusskih** [comment]
yeah. I can reproduce it. trying to figure out "why"

**Comment by srusskih** [comment]
Something bad with Package Control.
Could reproduce the issue when I removed manually dependencies from 
`/Users/sr/Library/Application Support/Sublime Text 3/Packages`

**Workaround:**
1. Remove `55-mdpopups.py` from `/Users/sr/Library/Application Support/Sublime Text 3/Installed Packages/0_package_control_loader.sublime-package`
2. Restart Sublime
3. Try install Jedi one more time.
