### ISSUE TITLE
Return type detection not working

### ISSUE THREAD

**Issue by Souyama** [srusskih/SublimeJEDI#239]
Hi,
Your plugin works great except for the fact that it doesn't seem to handle the returned values of functions (or even parameters for that matter).

For example I type, say `input()`. Well by logic it returns a string, So the next suggestion list will be whatever exists in the `str` class. Say if I want `input().split()` The `split `function doesn't appear in the suggestion list neither does the jump to `definition `or show `docstring `option. Perhaps you meant it as a failsafe for handling the loose typing of names in Python but is there a way to enable or disable this option, or limit the suggestion to only be active if the function returns a single known datatype?

Thank you.

**Comment by Souyama** [comment]
On second thought it, works for [PEP 3107](http://www.python.org/dev/peps/pep-3107/) but just not for normal everyday convention. Still it would be great if the function returns value of a known singular return type, then implement the JEDI suggestion.

**Comment by srusskih** [comment]
@Souyama sorry but that goes out of plugin responsibility due to we using existing auto-completion library "jedi" with all features that it provides for us. Try to request the feature here https://github.com/davidhalter/jedi
