### ISSUE TITLE
Blink completion

### ISSUE THREAD

**Issue by pochemuto** [srusskih/SublimeJEDI#243]
First list appears for few milliseconds

![screencast 2018-05-10 13-55-27 mp4 2018-05-10 14-36-26](https://user-images.githubusercontent.com/690543/39867847-9528a626-545f-11e8-94d9-e60105e7f483.png)
![screencast 2018-05-10 13-55-27 mp4 2018-05-10 14-36-43](https://user-images.githubusercontent.com/690543/39867851-9720c698-545f-11e8-881e-6fe35265ec1f.png)

**Comment by srusskih** [comment]
ST2 or ST3 ?
what version ?

**Comment by pochemuto** [comment]
3.0 Build 3170, it also was at previous release

**Comment by srusskih** [comment]
@pochemuto please check if #244 works for you, I drop async completion to rid of blinking.

**Comment by pochemuto** [comment]
yes, now it's not blinking! Thanks!

**Comment by srusskih** [comment]
@pochemuto could you please use PR bit to make sure if it perform well?
there possible lags up to 3 seconds due to timeout on sync call

**Comment by pochemuto** [comment]
I would like test it a few weeks

**Comment by srusskih** [comment]
thanks!

**Comment by pochemuto** [comment]
I've been using this PR since then and I didn't get any issues. Thanks!

**Comment by srusskih** [comment]
@pochemuto thank for your feed back!
