### ISSUE TITLE
Show function definitions on hover

### ISSUE THREAD

**Issue by donileo** [srusskih/SublimeJEDI#261]
Is there a way to get the tooltips to show the function definitions when hovering over an autocompleted function. So in the picture below when hovering over the sleep autocompletion menu it'd be nice to have the function docs on the side. Or maybe have a tooltip that shows another popup with the documentation like VSCode does.

<img width="373" alt="screen shot 2018-07-22 at 3 30 53 am" src="https://user-images.githubusercontent.com/1881038/43043334-be7e4fce-8d5f-11e8-8a4d-412bb8027297.png">

**Comment by srusskih** [comment]
duplication of #207
