### ISSUE TITLE
Recognize function arguments in function body

### ISSUE THREAD

**Issue by hadisfr** [srusskih/SublimeJEDI#265]
It seems that function arguments don't be recognized in function body and no auto-complete is done about them. I don't remember is it a new issue or there were such behaviour in previous versions, too.  
Is this something related to SublimeJEDI or Jedi itself?

**Comment by srusskih** [comment]
Can remember such feature. Could you please describe more?

**Comment by hadisfr** [comment]
### Example
A simple example:

```python
var1 = 1


class C(object):
    var4 = 4

    def func2(self, var5, var6):
        pass


def func1(var2, var3):
    pass


def main():
    func1(2, 3)
    C().func2(5, 6)


if __name__ == '__main__':
    main()

```

### Current (buggy) behaviour
![image](https://user-images.githubusercontent.com/24562441/44028077-f899c020-9f0d-11e8-90a0-bf423fe3f4f4.png)
![image](https://user-images.githubusercontent.com/24562441/44028084-fbc94e5a-9f0d-11e8-8107-fafad17532ff.png)

### Expected (correct) behaviour
At `func1`, I expected `var1`, `var2`, and `var3` to be on the list.  
At `func2`, I expected `var1`, `var4`, and `var5` to be on the list.

**Comment by srusskih** [comment]
yeap, behavior was updated. and i can't remember why.

**Comment by hadisfr** [comment]
Is it possible to change it to the previous one? Or it's up to JEDI?

**Comment by srusskih** [comment]
yeap. going to fix it.
