### ISSUE TITLE
Duplicate entries in in function args completion

### ISSUE THREAD

**Issue by hadisfr** [srusskih/SublimeJEDI#269]
I'm getting exactly two number of every argument in completion suggestions when calling _my own functions_.

E.g.:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/24562441/44309449-0366c700-a3dc-11e8-9dfa-4506f0d292d0.png">
Signature of that function:
```python
def get_data(self, condition, cond, max_length=None):
```

Where's the problem?

**Comment by srusskih** [comment]
https://github.com/srusskih/SublimeJEDI/commit/30b5c5f2d96bd68cb9edebdff51b547e1d9459f1

**Comment by hadisfr** [comment]
Sorry, I don't know why I didn't remember #267 when creating this while I had seen that before. 🙄 
I'm using package control's one.

**Comment by srusskih** [comment]
Maybe, I should release the fix...

**Comment by hadisfr** [comment]
@srusskih Thank you!
