### ISSUE TITLE
Jedi freezes ST and causes very high RAM usage.

### ISSUE THREAD

**Issue by deathaxe** [srusskih/SublimeJEDI#271]
### Description

1. An python file of a Sublime Text package is open.
2. Enter `from collections import S` into the first line.

ST suddenly freezes. After a while the console shows some output error. The CPU usage of the plugin_host.exe increases to 100% for one core. The RAM usage increases up to 1.2GB.

I was faced to that issue several times. Sometimes RAM usage even increases and stays at 2.5GB!

### Console Output

```
Traceback (most recent call last):
  File "C:\Apps\Sublime Text 3\sublime_plugin.py", line 685, in on_query_completions
    res = vel.on_query_completions(prefix, locations)
  File "C:\Apps\Sublime Text 3\Data\Packages\Jedi - Python autocompletion\sublime_jedi\completion.py", line 154, in on_query_completions
    location=locations[0]
  File "C:\Apps\Sublime Text 3\Data\Packages\Jedi - Python autocompletion\sublime_jedi\daemon.py", line 83, in ask_daemon_with_timeout
    return request.result(timeout=timeout)
  File "./python3.3/concurrent/futures/_base.py", line 403, in result
concurrent.futures._base.TimeoutError
```

### TaskManager

![screenshot](https://user-images.githubusercontent.com/16542113/44616667-371a7480-a854-11e8-9d69-4b2530dfc3ac.png)

### Infos

- Win10 Pro 1803 x64
- ST 3176 x64
- Jedi v0.13.4
- Running python 3.7
- jedi-0.12.1
- parso-0.3.1

```
'PYTHONPATH': ';C:\\Apps\\Sublime Text 3\\Data\\Lib\\python3.3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\wcwidth\\all;C:\\Apps\\Sublime Text 3\\Data\\Packages\\sublime_lib\\st3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\tabulate\\all;C:\\Apps\\Sublime Text 3\\Data\\Packages\\PYTHON~1\\st3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\pyyaml\\st3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\dateutil\\all;C:\\Apps\\Sublime Text 3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\pygments\\all;C:\\Apps\\Sublime Text 3\\Data\\Packages\\jsonschema\\all;C:\\Apps\\Sublime Text 3\\python3.3.zip;C:\\Apps\\Sublime Text 3\\Data\\Packages\\pyte\\all;C:\\Apps\\Sublime Text 3\\Data\\Packages\\python-jinja2\\all;C:\\Apps\\Sublime Text 3\\Data\\Packages\\MARKUP~1\\all;C:\\Apps\\Sublime Text 3\\Data\\Packages\\backrefs\\st3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\mdpopups\\st3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\lxml\\st3_windows_x64;C:\\Apps\\Sublime Text 3\\Data\\Packages\\Jedi - Python autocompletion\\dependencies;C:\\Apps\\Sublime Text 3\\Data\\Packages;C:\\Apps\\Sublime Text 3\\Data\\Packages\\pymdownx\\st3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\ruamel-yaml\\st3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\coverage\\st3_windows_x64;C:\\Apps\\Sublime Text 3\\Data\\Packages\\pathtools\\all;C:\\Apps\\Sublime Text 3\\Data\\Packages\\pywinpty\\st3_windows_x64;C:\\Apps\\Sublime Text 3\\Data\\Packages\\regex\\st3_windows_x64;C:\\Apps\\Sublime Text 3\\Data\\Packages\\yaml_macros_engine\\st3;C:\\Apps\\Sublime Text 3\\Data\\Packages\\watchdog\\all',
```

**Comment by kylebebak** [comment]
I can confirm that some recent release of Jedi caused a big hit to performance. ST now hangs when trying to populate the autocomplete list, often for as long as a second.

I've been using this plugin for about 5 years and this has never been an issue before.

OSX, ST 3176, Jedi 0.13.4.

**Comment by deathaxe** [comment]
The issue is 100% reproducible with my setup. 

Guess it's somehow related with the provided PYTHONPATH and the dependencies being passed to Jedi.
I use the following little script, which adds the ST's sys.path to the environment. This enables Jedi to see all dependencies automatically. I don't need to care about Package Control installing new ones.

```
import os
import sys


def update_path_list(var_name, path_list):
    paths = os.environ.get(var_name, "").split(os.pathsep)
    paths += path_list
    os.environ[var_name] = os.pathsep.join(paths)


# add ST's python search paths to the local environment
update_path_list("PYTHONPATH", sys.path)
```

Reading the console error message carefully makes me wonder about the line containing the python3.3. Jedi runs a python deamon, which runs on the external interpreter (3.7) here. Maybe one of the sys.path entries conflicts with the standalone python 3.7?

Maybe I even got the culprit - not sure. ST's sys.path includes _python3.3.zip_. Looks like the python 3.7 tries to use it rather than its own stdlib and crashes in the `concurrent` package.

I disabled my script and put all sys.path entries except the python3.3.zip to jedi's "python_package_paths". Seems to work.

**Comment by kylebebak** [comment]
@srusskih 

I haven't tried with a fresh installation, but let me explain what I did.

I removed SublimeJEDI, started typing some characters into a function call, and the autocomplete list appeared instantaneously.

I then reinstalled SublimeJEDI, started typing the same characters into the same function call, and Sublime Text hangs for nearly a second before showing the autocomplete list.

In my opinion, this is convincing evidence that SublimeJEDI is causing the slowdown. I've isolated the variable that causes the slowdown. The variable is whether or not SublimeJEDI is installed. This didn't start happening until a couple of weeks ago, maybe less. What do you think?

**Comment by srusskih** [comment]
@kylebebak  first completion is slow - yeap, that's ok. next completion should be much faster.

But, I still can't reproduce editor slowdown to fix the issue. That's why I'm asking to experiment.

**Comment by srusskih** [comment]
@deathaxe thanks. seems like `parso` (or not) tried to parse to much.

**Comment by kylebebak** [comment]
@srusskih 

I made a small video to show the slowdown, where I type "url" as an argument into a function 4 separate times.

Each time I'm typing "u-r-l" as quickly as I can, but ST hangs visibly for more than half a second after "u" appears but before "r" appears.

I've been using Jedi for years and I've never seen slowdown like this.

@deathaxe 
Could you show me your "python_package_paths" setting for Jedi, so I can see if this gets rid of the slowdown on my machine?

**Comment by deathaxe** [comment]
Just added  a `webbrowser.get(...).open()` line somewhere in my code. The first time I enter url, it takes quite a long time - 1 to 3 seconds. But after that the delays seem constant at something like 0.3 to 0.6s.


The culprit for high RAM was the second line in my case.

```
// These settings override Default settings for the package
{
    "python_package_paths": [
        "C:\\Apps\\Sublime Text 3",
        // "C:\\Apps\\Sublime Text 3\\python3.3.zip",
        "C:\\Apps\\Sublime Text 3\\Data\\Lib\\python3.3",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\pygments\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\ruamel-yaml\\st3",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\sublime_lib\\st3",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\tabulate\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\lxml\\st3_windows_x64",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\pathtools\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\wcwidth\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\coverage\\st3_windows_x64",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\watchdog\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\pywinpty\\st3_windows_x64",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\backrefs\\st3",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\dateutil\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\MARKUP~1\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\pymdownx\\st3",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\pyte\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\PYTHON~1\\st3",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\pyyaml\\st3",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\regex\\st3_windows_x64",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\yaml_macros_engine\\st3",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\python-jinja2\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\jsonschema\\all",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\mdpopups\\st3",
        "C:\\Apps\\Sublime Text 3\\Data\\Packages\\Jedi - Python autocompletion\\dependencies",
    ],
}
```

**Comment by kylebebak** [comment]
Hmm...

My settings for Jedi are just the default settings. In particular, `python_package_paths` is an empty list. So something else is causing the slowdown for me. At least now we have a reproducible case.

Just typing and retyping various parts of the following causes slowdown that doesn't get better with repeated attempts. But maybe this is to be expected. @srusskih Any ideas?

~~~py
import webbrowser
webbrowser.get('abc').open(url)
~~~

**Comment by mew1033** [comment]
I'm having the same issue with the same error:

    Traceback (most recent call last):
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 685, in on_query_completions
        res = vel.on_query_completions(prefix, locations)
      File "C:\Users\Chandler\AppData\Roaming\Sublime Text 3\Packages\Jedi - Python autocompletion\sublime_jedi\completion.py", line 154, in on_query_completions
        location=locations[0]
      File "C:\Users\Chandler\AppData\Roaming\Sublime Text 3\Packages\Jedi - Python autocompletion\sublime_jedi\daemon.py", line 83, in ask_daemon_with_timeout
        return request.result(timeout=timeout)
      File "./python3.3/concurrent/futures/_base.py", line 403, in result
    concurrent.futures._base.TimeoutError

**Comment by ac130kz** [comment]
Same issue, even though my "python_interpreter": "/usr/bin/python3":

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 685, in on_query_completions
    res = vel.on_query_completions(prefix, locations)
  File "/home/ac130kz/.config/sublime-text-3/Packages/Jedi - Python autocompletion/sublime_jedi/completion.py", line 154, in on_query_completions
    location=locations[0]
  File "/home/ac130kz/.config/sublime-text-3/Packages/Jedi - Python autocompletion/sublime_jedi/daemon.py", line 83, in ask_daemon_with_timeout
    return request.result(timeout=timeout)
  File "./python3.3/concurrent/futures/_base.py", line 403, in result
concurrent.futures._base.TimeoutError
```

**Comment by mew1033** [comment]
@srusskih Is there anything I can do to help locate this issue and reproduce it? I've disabled Sublime Jedi because of the slowdowns and I'm missing it.

**Comment by srusskih** [comment]
@mew1033 do you have a way how it can be reproduced?

**Comment by Aero-fish** [comment]
I had a similar issue. Maybe it is to do with typing.


```
from .module import complex_class

class heuristic():

    def run_alg(self):
        for i in range(10):
            c = complex_class
            value = c.get_value()
            # Adding typing for 'value' solves the lag.
            # value: float = c.get_value()

            if value > 10:
                pass
            else:
                c.set_value(10)  # Auto complete is normal at this line

            c.print_value()  # Auto complete is laggy at this line and after.
```

**Comment by barathbheeman** [comment]
any update on the issue? with jedi st is literally unusable with up to 5 seconds of delay every time I try type anything.

**Comment by ninja542** [comment]
yeah, I recently noticed this, and I had to remove the package, but this package was pretty useful and I hope I can continue using it :/

**Comment by srusskih** [comment]
> any update on the issue? with jedi st is literally unusable with up to 5 seconds of delay every time I try type anything.

@barathbheeman sounds really bad, it looks like Jedi by it self are really slow on your env.

**Comment by srusskih** [comment]
as workaround feel free install one of previous versions :(

**Comment by srusskih** [comment]
Have found this https://github.com/davidhalter/jedi/issues/1242

**Comment by srusskih** [comment]
please check a new release

**Comment by mew1033** [comment]
I'm still having slowdowns on the latest release. Windows 10, Sublime 3, Python 2.

**Comment by kylebebak** [comment]
I know this may not be helpful, but I can also still confirm that auto-complete for Python files using Sublime Jedi is much slower than auto-complete for any other language I use in ST.

Entering `if var is None:` into the editor causes noticeable lag as I type `if`, `var`, and `None`.

If I retype `if var is None:` again, right below the previous `if var is None`, I run into the same lag. In other words, it doesn't get faster after fetching completions for a given piece of text.

Who knows if this is an issue with Sublime Jedi or with Jedi, but this is obviously not how this is supposed to work. And again, in the past (before August 2018 for me) lag was never a problem with this plugin. I just disabled Sublime Jedi =(

**Comment by kylebebak** [comment]
I added the following to `User/Python.sublime-settings` to disable auto-complete except on `.`, as suggested in readme.

```json
"auto_complete_triggers": [{"selector": "source.python", "characters": "."}],
"auto_complete_selector": "-",
```

This is nice, because ST no longer lags like crazy trying to fetch the Jedi auto-completions, and you still get the info popup if you hover over text, and you get auto-completions for methods and properties and anything that's preceded by `.`.

But, it kills the rest of Sublime Text's auto-complete functionality for your Python files, which is totally unacceptable. It's almost funny to me that the readme suggests doing this not just in your Python files, but in all your ST files, by placing the above text in `User/Preferences.sublime-settings`.

The workaround to me seems to be creating a setting that **only** disables auto-complete for Sublime Jedi, while keeping the rest of its functionality. I will look into doing this.

**Comment by srusskih** [comment]
@kylebebak thanks for a feedback. 
If you would have a time and inspiration could you please collect some logs to investigate the issue? 
how to set up logging you can find here https://github.com/srusskih/SublimeJEDI#logging 

thanks. will try to look what I can find.

**Comment by kylebebak** [comment]
Hey @srusskih 

Thanks (again) for the super fast response!

I opened a PR, https://github.com/srusskih/SublimeJEDI/pull/286, that addresses this slowdown in a different way. Please let me know what you think!

If you'd still like me to look into logging, I can do that this weekend.
