### ISSUE TITLE
Jedi auto-selects an auto-completed parameter suggestion

### ISSUE THREAD

**Issue by romanovzky** [srusskih/SublimeJEDI#273]
Hi there,

I've noticed a behaviour that is a huge papercut. When accepting an auto-complete parameter suggestion (as in a function parameter), ST with Jedi automatically selects the suggestion leading to the next keystroke replacing it with whatever you press.

Way to reproduce this in my setup:

```python
def function(par=10):
    return par

function(p)
```

When typing `p`, by either pressing `tab` or `enter` to accept `par` as auto-completion suggestion, ST with Jedi correctly auto-completes with `par` but this comes selected, meaning that pressing for example `=` will replace `par` by `=`:

```python
function(=)
```

**Comment by srusskih** [comment]
Sounds like "OK". `par` inserted as "ST snippet" and an user are able to do what ever she want with this.

**Comment by srusskih** [comment]
An idea as possible feature,- is add an option that allow complete functions signatures with snippets or not, like:

`"signature_completion_as_snippet": true"`

but it feels like a try to write own editor or change ST behavior

**Comment by kkew3** [comment]
I'm not very clear about how sublime text addresses the snippet, but apparently it doesn't quite make sense for user to do whatever with it when the auto-completed-and-selected parameter is a keyword argument. For example,

```python
def f(par=10, another_par=20):
    ...   # some implementation
```

When typing `f(an` it suggests `f(another_par` with `another_par` selected. However, the only option the user has for now is to undo the selection and goes on typing `=` and the intended value. There's no other option that retains the semantics. While the same logic applies to positional arguments, it does not apply to keyword arguments. Thanks.

**Comment by srusskih** [comment]
it's hard to explain in words, I hope this GIFs helps

`"auto_complete_function_params": "all",`

![ex1-full-complete](https://user-images.githubusercontent.com/340727/54382171-20285c00-4698-11e9-9dea-ef529fc27908.gif)

`"auto_complete_function_params": "required",`
![ex1-required-replacement](https://user-images.githubusercontent.com/340727/54382172-20285c00-4698-11e9-9a67-55388d53a4fc.gif)

![ex2-required-kwargs](https://user-images.githubusercontent.com/340727/54382176-21598900-4698-11e9-99e7-713ec230e952.gif)

![ex3-required-replacemt_var](https://user-images.githubusercontent.com/340727/54382177-21f21f80-4698-11e9-8413-9b77784ceae6.gif)

![ex4-required-var](https://user-images.githubusercontent.com/340727/54382178-21f21f80-4698-11e9-9ae1-4dcaaa190d37.gif)
