### ISSUE TITLE
Do not show the entire changelog for each update

### ISSUE THREAD

**Issue by FichteFoll** [srusskih/SublimeJEDI#274]
Please do not specify `CHANGELOG.md` for each update in `messages.json`. It will cause the *entire* changelog to be displayed for *each* version that was skipped in addition to the newest update. Package Control automatically only shows changelogs for versions since the latest update. Having this *huge* changelog displayed for each update, possibly weekly, is just annoying and unnecessary.

**Comment by srusskih** [comment]
@FichteFoll thanks for feed back. will do something with this next release.

Maybe you have some solution to do such routine automatically? (:

**Comment by FichteFoll** [comment]
Not yet. Ideally PC would find all text files in a messages subfolder automatically (there is an issue for that, but nobody has spent the time to implement it yet), so you wouldn't have to update messages.json manually. I don't keep a combined changelog file anymore, but it would be trivial to generate that with some shell scripting.

**Comment by srusskih** [comment]
done
