### ISSUE TITLE
Write python3.6 use jedi sublime on mac-os 10.11.6 always freezes. 

### ISSUE THREAD

**Issue by lim1942** [srusskih/SublimeJEDI#279]
Sublime always freeze ,mouse  pointer can`t move

**Comment by srusskih** [comment]
I'm using python3.6 on my OSX 10.14.2 (18C54) - works fine :(

After what action it stacks?

**Comment by lim1942** [comment]
> I'm using python3.6 on my OSX 10.14.2 (18C54) - works fine :(
> 
> After what action it freezes (stacks)?

tks, after update os to OSX 10.14,thi

> I'm using python3.6 on my OSX 10.14.2 (18C54) - works fine :(
> 
> After what action it freezes (stacks)?

Tks ,after update my os to OXS 10.14.2,this problem is gone ~

**Comment by srusskih** [comment]
wow. @lim1942 sounds great. happy coding :)
