### ISSUE TITLE
TypeError: run() missing 1 required positional argument: 'base_file'

### ISSUE THREAD

**Issue by ivanlmj** [srusskih/SublimeJEDI#283]
Sublime 3 cannot find the package for installation and on the Sublime console, it show this:

    reloading plugin Jedi - Python autocompletion.__init__
    generating meta info summary
    reloading plugin Package Control.1_reloader
    reloading plugin Package Control.2_bootstrap
    reloading plugin Package Control.Package Control
    Package Control: Not running package cleanup since bootstrapping is not yet complete
    reloading settings Packages/Package Control/Package Control.sublime-settings
    reloading plugin 0_package_control_loader.00-package_control
    reloading settings Packages/User/Package Control.sublime-settings
    reloading settings Packages/User/Package Control.sublime-settings
    Traceback (most recent call last):
    File "/opt/sublime_text/sublime_plugin.py", line 1007, in run_
        return self.run()
TypeError: run() missing 1 required positional argument: 'base_file'

**Comment by srusskih** [comment]
that's quite interesting.
could you please share you ST3 build and plugin version? :) 
thanks

**Comment by srusskih** [comment]
>cannot find the package for installation 
sounds like non-jedi issue...

**Comment by ivanlmj** [comment]
Version 3.1.1.

Seems like a restart was need (I guess).

 ### CONSOLE

    reloading plugin Default.arithmetic
    reloading plugin Default.auto_indent_tag
    reloading plugin Default.block
    reloading plugin Default.colors
    reloading plugin Default.comment
    reloading plugin Default.convert_color_scheme
    reloading plugin Default.convert_syntax
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.install_package_control
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_context_url
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.profile
    reloading plugin Default.quick_panel
    reloading plugin Default.rename
    reloading plugin Default.run_syntax_tests
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.settings
    reloading plugin Default.show_scope_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin Default.ui
    reloading plugin CSS.css_completions
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin ShellScript.ShellScript
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.01-pygments
    reloading plugin 0_package_control_loader.50-markupsafe
    reloading plugin 0_package_control_loader.50-python-markdown
    reloading plugin 0_package_control_loader.51-python-jinja2
    reloading plugin 0_package_control_loader.55-mdpopups
    reloading plugin Package Control.1_reloader
    reloading plugin Package Control.2_bootstrap
    reloading plugin Package Control.Package Control
    reloading plugin Jedi - Python autocompletion.__init__
    plugins loaded
    Package Control: No updated packages

Tks @srusskih

**Comment by srusskih** [comment]
Always welcome :)
