### ISSUE TITLE
Can't install Jedi - python autocompletion.

### ISSUE THREAD

**Issue by ThePonyCoder** [srusskih/SublimeJEDI#293]
It looks like Jedi - python autocompletion can't installed on st3 portable

**Comment by typorian** [comment]
I currently also have the problem that I cannot install the package. The console log simply states:

Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: The dependency 'markupsafe' is not available
Package Control: The dependency 'markupsafe' could not be installed or updated

**Comment by srusskih** [comment]
@typorian I see `markupsafe` in repository 
https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json#L396
looks like something wrong with configuration

**Comment by typorian** [comment]
@srusskih I get the exact same issue with a freshly downloaded sublime text portable. I am not sure if this is actually a Jedi issue, it might as well be a sublime issue.

**Comment by ThePonyCoder** [comment]
Problem isn't with Jedi, it is with sublime portable

**Comment by carter54** [comment]
it is Jedi not support portable python
https://jedi.readthedocs.io/en/latest/docs/api.html#environments
```
Ignores virtualenvs and returns the Python versions that were installed on your system. This might return nothing, if you’re running Python e.g. from a portable version.
```
