### ISSUE TITLE
Absent `__init__.py` breaks autocomplete and goto functionality.

### ISSUE THREAD

**Issue by ak04nv** [srusskih/SublimeJEDI#312]
Starting Python version 3.3 it uses [Implicit Namespace Packages](https://www.python.org/dev/peps/pep-0420/). This Python version has been included in the Sublime Text 3. But if an empty `__init__.py` isn't contained in the module autocomplete and goto definition doesn't work cause `goto` daemon returns an empty suggestions list.

**Comment by srusskih** [comment]
Looks like https://github.com/davidhalter/jedi is better place for this kind of issue.

**Comment by ak04nv** [comment]
@srusskih got you, thanks! :)

**Comment by ak04nv** [comment]
@srusskih 
It seems jedi's version is too old.
https://github.com/davidhalter/jedi/issues/1516
Can you update it?

**Comment by ak04nv** [comment]
I've installed the package via package control. My current version of the package is 0.16
But in the `.config/sublime-text-3/Packages/Jedi - Python autocompletion/dependencies/jedi` folder in the `__init__.py` file I see:
```python
__version__ = '0.14.1'
```

**Comment by srusskih** [comment]
they do not correlate. looks like I should release new version :)

**Comment by srusskih** [comment]
@ak04nv I have no idea how quick it would be available 
but here it is 
https://github.com/srusskih/SublimeJEDI/releases/tag/0.17.0
