### ISSUE TITLE
incorrect parameters completion

### ISSUE THREAD

**Issue by srusskih** [srusskih/SublimeJEDI#48]
``` python
def test(a1, a2, a3):
    pass


def test2(b1, b2):
    pass
```

After **(** presed

``` python
test(a1, a2, a3)
```

selected **a1**  replaced on **test2(**

Actual:

``` python
test(test2(a1, a2, a3), a2, a3)
```

Ecpected:

``` python
test(test2(b1, b2), a2, a3)
```

**Comment by hadisfr** [comment]
I'm getting correct
```python
test(test2(b1, b2)
```
in the current version **only** when I cut the rest of statement (`, a2, a3)`).

When that part still exists, no autocompletion happens.
