### ISSUE TITLE
Nothing happen and no error reported

### ISSUE THREAD

**Issue by daniele-niero** [srusskih/SublimeJEDI#74]
Hello,

I installed SublimeJedi through Package Control but it seems like the plugin is doing nothing.

No matter what I try to set in the settings, the plugin simply stay silent, don't work and don't report errors either...

Is there something I can do to at least get some logs or error and trying to understand what is going wrong?

I'm a windows 7 and I trying to autocomplete with python2.6

**Comment by SmartManoj** [comment]
Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: The dependency 'markupsafe' is not available
Package Control: The dependency 'markupsafe' could not be installed or updated

**Comment by srusskih** [comment]
it looks like issue with Package Control

I see "markupsafe" in PC https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json#L396

I can't do anything here.
